name: Update README

on:
  push:
    branches:
      - main  # replace with your default branch if different

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This will now run on Node.js 16 by default

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python update_readme.py
