name: Update README

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update README
      run: python update_readme.py
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
